name: kyc_analytics
version: 1.0.0
config-version: 2
profile: kyc_analytics

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]
analysis-paths: ["analyses"]

target-path: target
clean-targets: ["target", "dbt_packages"]

models:
  kyc_analytics:
    +materialized: view
    staging:
      +schema: staging
    intermediate:
      +schema: intermediate
      +materialized: table
    marts:
      +schema: marts
      +materialized: table

seeds:
  kyc_analytics:
    sample_kyc_events:
      +schema: raw
      +alias: silver_kyc_events
